ITM-Kitware/align-system

algorithms/llama_index.py, baseline_system_local_files.py, requirements.txt
Add the llama_index algorithm.
=> Initial integration of llama index algorithm

CHANGELOG.md, align_system/cli/run_align_system.py, align_system/utils/enums.py
All new probe types appear to be effectively multiple choice.
=> Handle new probe types for TA1 APIs

poetry.lock
=> Upate poetry.lock

LICENSE, NOTICE
Add open source license based on Kitware recommendation ([link](https://docs.google.com/document/d/1O6bhemX6vxBW3DwyNqKv9gVftfl-g9AM4dCbYETFPVM/edit))
=> Add Apache 2.0 license

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/configs/experiment/examples/outlines_sampler.yaml, align_system/configs/experiment/metrics_refinement_evaluation/outlines_llama3_adept_high_training.yaml, align_system/configs/experiment/metrics_refinement_evaluation/outlines_llama3_adept_low_training.yaml, align_system/configs/experiment/metrics_refinement_evaluation/outlines_llama3_soartech_high_training.yaml, align_system/configs/experiment/metrics_refinement_evaluation/outlines_llama3_soartech_low_training.yaml
FYSA @jadie1 @eveenhuis , I'm going to merge this soon but this MR tweaks both outlines ADMs (regular and regression) to support different outlines samplers (see the example experiment included).
=> Add Outlines Sampler Parameter

align_system/algorithms/lib/persona/provider.py
Previously, the persona provider didn't correctly cache backstories in a repeatable way. This corrects it so that:
- If "Cache" is True, then the backstories for the current alignment will be cached (or returned from an existing cache)
- If "Cache" is False, then the backstories for the current alignment target will be cleared, and refreshed.
=> Fix bug in personas provider caching

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/prompt_engineering/outlines_prompts.py
- Prevent overwriting action data when using followup prompts
- Add aid followup prompt for API changes
=> Followup prompt fixes

align_system/utils/kde_utils.py
Adds fix for JS distance NaN value when KDEs are close, following https://github.com/ITM-Soartech/ta1-server-mvp/commit/cfb0c408b7b5fab687d26d13a99ff374b7f79139
=> Fix for JS distance NaN value when KDEs are close

CHANGELOG.md, align_system/cli/run_align_system.py, align_system/configs/action_based.yaml
Adds capability and configuration option to time the `choose_action` method and create a report summarizing those times.
=> Add choose_action timing configuration option

CHANGELOG.md, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/alignment_utils.py
I've updated the comparative regression justification to include the outcome prediction (if on) and the score reasoning from the best sample. To do this I had to update the alignment functions class to optionally return the index of the best sample.
=> Comparative regression justification update

align_system/algorithms/outlines_adm.py, align_system/cli/run_align_system.py, align_system/configs/experiment/dry_run_evaluation/random_eval.yaml, align_system/prompt_engineering/outlines_prompts.py
Fixes to get a complete baseline run through current eval scenarios
=> Eval scenario fixes

align_system/algorithms/outlines_regression_adm_comparative.py
Small bug fix to fix fstring quote syntax issue
=> Fix fstring quotes

CHANGELOG.md, align_system/algorithms/hybrid_kaleido_adm.py, align_system/algorithms/kaleido_adm.py, align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_adm.py, align_system/configs/adm/hybrid_kaleido.yaml, align_system/utils/alignment_utils.py
Updated Hybrid Kaleido ADM to use the Outlines ADM for action parameter completion, and update to make use of KDE based alignment utils for SoarTech scenarios. (WIP)
=> Update Hybrid Kaleido ADM for DRE

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py
=> Add model 'precision' option for outlines adms

align_system/algorithms/outlines_hybrid_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/alignment_utils.py, align_system/utils/kde_utils.py
Convert `KDMAValue`s to dictionaries to access attributes consistently
@dmjoy Not sure we actually want to merge into main as is, but wanted you to have it in case you need it for eval runs. I may be overdoing the conversions/there may be a smarter way to do this
=> Convert KDMA target to dictionary

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/cli/run_align_system.py
Restrict unseen characters for all actions except MOVE_TO and MOVE_TO_EVAC
=> Restrict unseen characters

align_system/algorithms/outlines_hybrid_regression_adm.py, align_system/configs/adm/hybrid_regression.yaml, align_system/prompt_engineering/outlines_prompts.py
@dmjoy @eveenhuis 
This PR addresses updates to the prompting for the Hybrid Regression ADM based on recent updates to the training data. 
The path to the model weights for all 4 KDMAs have been updated in this MR.
=> Update Hybrid Regression Prompts

align_system/utils/incontext_utils.py
I found a couple small mistakes through running the ICL normalization benchmark. This tiny PR corrects them
=> ICL normalization corrections

align_system/algorithms/outlines_hybrid_regression_adm.py, align_system/cli/run_align_system.py, align_system/interfaces/ta3_caci_action_based_service.py
@aaron-bray PTAL, I think I've addressed each of your requests from the email thread.
=> Tweaks to log messages and input_output saving for easier parsing

CHANGELOG.md, align_system/cli/run_align_system.py, align_system/utils/hydrate_state.py
These changes are in support of the SoarTech alignment target(s) plotting script.
=> Tweaks to input-output file and saved alignment target

align_system/configs/experiment/phase1_evaluation/comp_reg_soartech_train.yaml, align_system/configs/experiment/phase1_evaluation/random_soartech_train.yaml
@eveenhuis  and @dmjoy Adding additional experiment configs for phase1 ST train runs
=> Adding phase1 ST experiment configs

CHANGELOG.md, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/cli/run_align_system.py
Adds the option to filter out tag character from the available actions
=> Filter tag character

CHANGELOG.md, align_system/utils/incontext_utils.py
Add ICL example ordering configuration option
=> Add option to reverse ICL order

CHANGELOG.md, align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/cli/run_align_system.py
Will add CHANGELOG after test run confirms changes are working as expected.
=> Reset history on new scenario for history tracking ADMs

align_system/configs/experiment/phase1_evaluation/comp_reg_adept_eval.yaml, align_system/configs/experiment/phase1_evaluation/comp_reg_adept_ingroup_bias_train.yaml, align_system/configs/experiment/phase1_evaluation/comp_reg_adept_ingroup_bias_train_sample.yaml, align_system/configs/experiment/phase1_evaluation/comp_reg_adept_moral_judgement_train.yaml, align_system/configs/experiment/phase1_evaluation/comp_reg_adept_moral_judgement_train_sample.yaml
Pending results of the current sweeps
=> Current best ADEPT configs

CHANGELOG.md, align_system/algorithms/lib/persona/provider.py, align_system/algorithms/outlines_persona_adm.py, align_system/configs/adm/outlines_persona.yaml, align_system/configs/experiment/dry_run_evaluation/outlines_personas_adept_ingroup_bias_train.yaml, align_system/configs/experiment/dry_run_evaluation/outlines_personas_adept_moral_judgement_train.yaml, align_system/utils/alignment_utils.py, align_system/utils/voting.py
Hi @DavidMChan here's my initial integration of the personas provider with an outlines based ADM.  I've made one or two tweaks to the provider itself, the most significant of which is adding the option to filter out backstory probes based on what KDMAs are in the alignment target (on by default).  The thinking here is that we don't want to potentially confuse the LLM with other KDMAs we're not interested in with respect to the target, but maybe it's critical to the approach in some way to include everything?  Would love to hear your thoughts there.
One limitation to this initial version is that we don't have a way yet to select personas using a distribution based alignment target (i.e. a KDE), interested on your input there as well.  We've considered sampling from the target distribution …
=> Outlines based personas ADM

align_system/configs/experiment/multi_kdma_evaluation/comp_reg_adept_ingroup_bias_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/comp_reg_adept_moral_judgement_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/comp_reg_soartech_qol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/comp_reg_soartech_vol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/hybrid_kaleido_adept_ingroup_bias_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/hybrid_kaleido_adept_moral_judgement_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/hybrid_kaleido_soartech_qol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/hybrid_kaleido_soartech_vol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_comp_reg_adept_ingroup_bias_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_comp_reg_adept_moral_judgement_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_comp_reg_soartech_qol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_comp_reg_soartech_vol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_hybrid_kaleido_adept_ingroup_bias_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_hybrid_kaleido_adept_moral_judgement_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_hybrid_kaleido_soartech_qol_eval_as_train.yaml, align_system/configs/experiment/multi_kdma_evaluation/relevance_hybrid_kaleido_soartech_vol_eval_as_train.yaml
Please take a look @jadie1 @eveenhuis and make sure I haven't made a mistake with the configs.  If you all run more experiments etc. feel free to update this branch directly, or I can merge it and you all can make follow-up MRs.
=> Tweaks for multi-KDMA experiment runs

align_system/configs/alignment_target/qol-group-target-1-final-eval.yaml, align_system/configs/alignment_target/qol-group-target-2-final-eval.yaml, align_system/configs/alignment_target/vol-group-target-1-final-eval.yaml, align_system/configs/alignment_target/vol-group-target-2-final-eval.yaml
@barry-ravichandran FYSA
(@jadie1 @eveenhuis just a heads up, the SoarTech group targets for Phase1 eval are getting renamed here to match the ID's used on the latest version of their server code)
=> Update Phase1 SoarTech group targets to their server convention

align_system/algorithms/alignment_adm_component.py, align_system/algorithms/misc_itm_adm_components.py, align_system/configs/adm/phase2_pipeline_relevance_oracle.yaml, align_system/configs/adm_component/misc/oracle_relevance.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_relevance_oracle.yaml
Adds oracle relevance pipeline and component
=> Relevance Oracle Pipeline

align_system/configs/adm_component/icl/phase2_comparative.yaml
Updates the search and medical ICL files for the new search vs stay train yaml
=> Updating ICL files for new search vs stay train

align_system/configs/attribute/merit_focus.yaml, align_system/configs/template/output_schema/phase2_comparative_regression_choice.yaml
Fixing score scale factor lookup for merit in align_system/configs/template/output_schema/phase2_comparative_regression_choice.yaml
=> Fixing score scale factor lookup for merit

CHANGELOG.md, docs/pipeline_adms.md
Update the Pipeline ADM docs to explain more complicated components etc. (using the comparative regression pipeline example).
=> Update pipeline ADM documentation

README.md
@dmjoy Update to the README to include the link to the ALIGN App.
=> Add ALIGN App link to README

align_system/configs/experiment/phase2_july_collab/pipeline_fewshot_comparative_regression_loo.yaml
Adding aligned ADM config with updated ICL and weighted alignment function
=> July aligned config 

align_system/algorithms/icl_adm_component.py, align_system/configs/experiment/integration_tests/pipeline_comp_reg_icl_bert_sim.yaml, align_system/configs/experiment/integration_tests/pipeline_comp_reg_icl_bert_sim_reverse.yaml, align_system/utils/incontext_utils.py, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim/.gitignore, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim/input_output.json, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim/raw_align_system.log, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim_reverse/.gitignore, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim_reverse/input_output.json, tests/data/expected_outputs/integration_tests/pipeline_comp_reg_icl_bert_sim_reverse/raw_align_system.log
Refactor ICL selection strategies to reduce code duplication.
=> Add similarity score to ICL examples in choice info

poetry.lock, pyproject.toml
=> Update to latest TA3 client version
