ITM-Kitware/align-system

.gitignore, algorithms/llama_index.py
Implemented retrieval toggle functionality for llama_index algorithm
Retrieval is enabled by default and can be disabled with the algorithm-kwargs command-line argument:
`--algorithm-kwargs '{"domain_docs_dir": "../data/DomainDocumentsPDF", "retrieval_enabled": false}' `
=> Implemented retrieval toggling for llama-index

align_system/algorithms/llama_2_single_kdma_adm.py
When the answer to a parsed treatment output is not an integer (can sometimes happen with the LLM), instead of failing on L959, try to parse the answer into an integer (and retry if impossible).
=> Fix minor bug in Llama-2 Single KDMA ADM When Answer is not integer

CHANGELOG.md, align_system/algorithms/pulse_tagging_adm.py
- Modified prompt
- Removed duplicated RED tag example, replaced with missing BLACK tag example
- Removed duplicated inference call in `identify_tag_color`
=> Updated START tagging ADM

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/configs/adm/outlines_regression_aligned.yaml, align_system/prompt_engineering/kdma_descriptions.yml, align_system/prompt_engineering/outlines_prompts.py
Implementation of the multi-KDMA/regression ADM using outlines
To test, call `run_align_system` with `adm=outlines_regression_aligned`
The ADM is implemented in [outlines_regression_adm.py](https://github.com/ITM-Kitware/align-system/blob/dev/outlines-regression/align_system/algorithms/outlines_regression_adm.py). It inherits functionality from [outlines_adm.py](https://github.com/ITM-Kitware/align-system/blob/dev/outlines-regression/align_system/algorithms/outlines_adm.py) but the `top_level_choose_action()` function is overwritten to do KDMA score prediction. Prompts and json schemas for this have been added to [outlines_prompts.py](https://github.com/ITM-Kitware/align-system/blob/dev/outlines-regression/align_system/prompt_engineering/outlines_prompts.py). I also added a …
=> Outlines Regression ADM

CHANGELOG.md, align_system/prompt_engineering/outlines_prompts.py
Adding `maxLength` to reasoning string outputs in json schemas so that they don't get stuck in repetitive loops and result in out of memory errors. Also fixed a couple of typos in regression prompts.
=> Limiting reasoning length to avoid OOM error

CHANGELOG.md, align_system/algorithms/outlines_adm.py, align_system/utils/voting.py, pyproject.toml
FYSA @eveenhuis @jadie1 here's the voting issue mitigation (stopping short of calling it a fix since there are still cases where things could fail, i.e. if there are no positive responses requested).
For the Outlines ADM this behavior is on by default now, can disable it from the command line with `+adm.inference_kwargs.filter_votes_to_positives=False`
Or in an experiment file with:
```
adm:
inference_kwargs:
filter_votes_to_positives: false
```
=> Dev/filter voting to positives; Version 0.4.1

align_system/algorithms/lib/persona/__init__.py, align_system/algorithms/lib/persona/provider.py, align_system/algorithms/lib/persona/templates.py, align_system/algorithms/lib/persona/types.py
This PR adds a "Persona Provider" which can be instantiated and queried to get dialogs relating to aligned personas. Right now, this *Should* behave almost identically to the personas ADM, but returns turns in the form needed by our updated ADMs such as the outlines ADM.
=> Add dialog provider for personas project

CHANGELOG.md, align_system/algorithms/outlines_adm.py
Fixed character selection to use the `character_id` associated with the selected action when available, otherwise send a follow up prompt. This prevents mismatch errors between selected choice and associated character
=> Character selection fix

CHANGELOG.md, align_system/algorithms/outlines_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/configs/adm/outlines_regression_aligned.yaml, align_system/configs/adm/outlines_regression_aligned/template.yaml, align_system/configs/adm/outlines_regression_aligned_comparative.yaml, align_system/configs/adm/outlines_regression_aligned_comparative/incontext.yaml, align_system/configs/adm/outlines_regression_aligned_comparative/template.yaml, align_system/prompt_engineering/outlines_prompts.py
- Adds another version of regression where KDMA scores are predicted for all responses/choices at once. Run by specifying `adm=outlines_regression_aligned_comparative`
- Adds template option for regression ADMs which can be turned on by setting `kdma_score_examples: True`. Run by specifying `adm=outlines_regression_aligned/template` or `adm=outlines_regression_aligned_comparative/template`
- Adds in-context examples with chain of thought reasoning for Adept KDMA's to regression ADMs. Run by specifying `adm=outlines_regression_aligned/incontext` or `adm=outlines_regression_aligned_comparative/incontext`
=> Comparative regression, templates, and COT ICL

align_system/algorithms/oracle_adm.py, align_system/configs/adm/oracle.yaml, align_system/utils/distribution_matching_utils.py
This adds the option for oracle alignment to KDE targets by randomly sampling a scalar target from the KDE.
Currently implemented options: 
- `distribution_matching`: `sample`
- `kde_norm`: `globalnorm`, `localnorm`, or `rawscores` (no functionality for `globalnormx_localnormy` yet)
The plan is to be able to add `distribution_matching` options to find the best approach.
@eveenhuis let me know if you have code improvement suggestions
@brianhhu this is a starting point for the idea you shared yesterday
=> Adding sampling approach to oracle for KDE target

align_system/algorithms/outlines_regression_adm_comparative.py, align_system/configs/adm/outlines_regression_aligned_comparative/incontext.yaml
Adds leave one out option for comparative regression ADM (conditioning only on scenario description) as a means to limit the effect of testing on training data
=> Add leave one out option for comparative regression ADM

align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/configs/adm/oracle.yaml, align_system/configs/experiment/dry_run_evaluation/random_soartech_qol_train.yaml, align_system/configs/experiment/dry_run_evaluation/random_soartech_vol_train.yaml, align_system/prompt_engineering/outlines_prompts.py, align_system/utils/distribution_matching_utils.py
- Add option to specify `num_kde_samples` for multiple samples in sample-based KDE target alignment for oracle 
- Adds `max-likelihood` KDE target alignment option for oracle and comparative regression ADMs
- Switches regression-based ADMs to use baseline prompt as the starting point for follow-ups. The old regression-specific prompt did not work with KDE targets. Now the baseline and regression-based ADMs have the exact same follow-up procedure 
- Updates the ST training experiments to use both train scenarios
=> KDE Alignment Functionality

CHANGELOG.md, align_system/utils/outlines_prompts_utils.py
This PR adds a scenario prompt that includes all structured character information that is not identical between characters. 
I accidentally merged this functionality to main already (https://github.com/ITM-Kitware/align-system/commit/8aa795afdd53372dadb568732363e4730e41d3cf), but in this PR I adds a bug fix for missing keys and updates the change log.
=> Character info promopt

CHANGELOG.md, align_system/cli/run_align_system.py, align_system/configs/experiment/dry_run_evaluation/hybrid_kaleido_adept_ingroup_bias_train.yaml, align_system/configs/experiment/dry_run_evaluation/hybrid_kaleido_adept_moral_judgement_train.yaml, align_system/configs/experiment/dry_run_evaluation/random_adept_ingroup_bias_train.yaml, align_system/configs/experiment/dry_run_evaluation/random_adept_moral_judgement_train.yaml
Update ADEPT train experiments to include new scenarios. The new scenarios identified the need to restrict pre-specified treatments when supplies are insufficient, so a fix for this is included.
=> Don't allow treatments when supplies aren't available

align_system/algorithms/outlines_hybrid_regression_adm.py, align_system/configs/adm/hybrid_regression.yaml
@dmjoy @eveenhuis 
This PR makes the following updates:
(1) Bugfix: Clip the regression model predictions to be between 0 and 1.
(2) Update `hybrid_regression.yaml` hydra config file to include the paths to the latest model weights.
=> Hybrid Regression Updates

CHANGELOG.md, align_system/utils/alignment_utils.py
This is a tiny PR that just ensures the values sampled from target KDEs are between 0 and 1
=> Clamp KDE target samples

CHANGELOG.md, align_system/algorithms/kaleido_adm.py, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_hybrid_regression_adm.py, align_system/algorithms/outlines_regression_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/configs/adm/outlines_regression_aligned_comparative/incontext.yaml, align_system/configs/adm/outlines_transformers_structured_aligned/incontext.yaml, align_system/utils/adm_utils.py, align_system/utils/incontext_utils.py
This PR has the following reformatting:
- Moves the `format_choices()` function from the `OutlinesTransformersADM` class in `outlines_adm.py` to a new utils file: `adm_utils.py`. This function is used across ADMs and in ICL so it's better as a standalone function. 
- Moves the ICL functionality to `incontext_utils.py`
I created the abstract class `IncontextExampleGenerator()` with an abstract method `set_icl_datasets()` that is called in initalization. The `set_icl_datasets()` function creates a dataset of possible ICL examples for each target KDMA, where each example is a dictionary with keys `prompt` and `response`. With this setup, we can create different implementations of `IncontextExampleGenerator()` (as I did with `ComparativeRegressionIncontextExampleGenerator()`) that have …
=> ICL Reformat

CHANGELOG.md, align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/alignment_utils.py
Adds a new alignment function which uses the JS divergence between the target and a cumulative KDE (constructed using choice history) . This option is added to the oracle and comparative regression ADMs. To use, specify `distribution_matching: cumulative_kde`
=> History-based cumulative KDE alignment option

CHANGELOG.md, align_system/algorithms/abstracts.py, align_system/algorithms/hybrid_kaleido_adm.py, align_system/algorithms/kaleido_adm.py, align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/algorithms/persona_adm.py, align_system/algorithms/random_adm.py, align_system/cli/run_align_system.py
This PR adjusts `choose_action()` to return a dictionary called `choice_info` in addition to the action to take. The `choice_info` dictionary contains ADM-specific info that would be difficult to parse from the log. `run_align_system.py` is updated to write `choice_info` to the `input_output.json` file for easier parsing. 
For comparative regression, the true and predicted KDMA values are logged and added to `choice_info`. This enables calculating the regression accuracy (MSE) from resulting `input_output.json` files, using this script: https://github.com/ITM-Kitware/scratch/blob/dev/regression_mse/calculate_mse.py
I added an empty dictionary for `choice_info` to the other ADMs for now. This could be updated down the line to include relevant info, such as the positive and negative votes …
=> Choice info in input_output.json

CHANGELOG.md, align_system/utils/alignment_utils.py
Removes possibility for divide by zero if all distances are zero when "misaligning." Also adds some additional error checking
=> Avoid potential divide by zero when misaligning

align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/alignment_utils.py
Small PR to:
- Fix bug - add missing kde_norm option for cumulative kde alignment
- Fix cumulative kde alignment to use dictionary syntax for the target_kdma since we call `target_kdma.to_dict()`
I don't think we need to update the change log for these small fixes
=> Small fixes for cumulative alignment 

CHANGELOG.md, align_system/configs/adm/outlines_regression_aligned_comparative/incontext.yaml, align_system/configs/adm/outlines_regression_aligned_comparative/incontext_phase1.yaml, align_system/utils/incontext_utils.py
Adds option to sort ICL examples responses (`sort_actions` in the `incontext` settings). 
This enables matching the ICL and probe response order when `sort_available_actions: true`
=> Adding option to sort ICL examples

CHANGELOG.md, align_system/algorithms/oracle_adm.py, align_system/algorithms/outlines_adm.py, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/configs/adm/outlines_regression_aligned_comparative/incontext.yaml, align_system/configs/adm/outlines_regression_aligned_comparative/incontext_phase1.yaml, align_system/configs/experiment/phase1_evaluation/random_adept_ingroup_bias_train.yaml, align_system/configs/experiment/phase1_evaluation/random_adept_moral_judgement_train.yaml, align_system/utils/incontext_utils.py
Adds character based LOO. Removes duplicate ICL examples, based on configured similarity measure. Phase 1 experiment directory created.
Note:
- `incontext.leave_one_out=false`  should now be specified as `incontext.leave_one_out=null`
- `incontext.leave_one_out=true`  should now be specified as `incontext.leave_one_out=scenario_description` (old behavior) or `incontext.leave_one_out=characters`
=> Add character-based LOO

CHANGELOG.md, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/prompt_engineering/kdma_descriptions.yml, align_system/utils/incontext_utils.py
Adds an option to include all unique structured character info in the comparative regression prompt. To use, set  `relevant_structured_character_info: ['all_unique']`in `kdma_descriptions.yml`
=> Option for all unique structured character info

align_system/utils/incontext_utils.py
Fixing an indentation error that was making it so only the first KDMA was included in the incontext dataset. With this fix alignment to multi-kdma targets works
=> Fixing indentation error for multi-kdma ICL

CHANGELOG.md, align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/incontext_utils.py
Added ICL example selection method that gives larger weight to examples with the same action types as the current probe. To use set `incontext.method` to `matching_actions`.
If there are no ICL examples with the same action types then `prompt_bert_similarity` is used.
=> Action type based ICL selection

CHANGELOG.md, align_system/utils/incontext_utils.py
This PR adds another ICL selection method. This one gives larger weight to examples with the same character ids as the current probe. To use set `incontext.method` to `matching_characters`.
If there are none with matching characters it uses the prompt bert similarity to select.
=> Add character based ICL selection

CHANGELOG.md, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Ingroup Bias-IO-high_MJ-high.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Ingroup Bias-IO-high_MJ-low.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Ingroup Bias-IO-low_MJ-high.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Ingroup Bias-IO-low_MJ-low.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Moral judgement-MJ-high_IO-high.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Moral judgement-MJ-high_IO-low.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Moral judgement-MJ-low-IO-high.yaml, align_system/configs/alignment_target/multi_target/ADEPT-DryRun-Moral judgement-MJ-low-IO-low.yaml
Adds multi-kdma targets for testing
`Ingroup Bias-lowhigh` means IB is low and MJ is high whereas `Moral judgement-lowhigh` means MJ is low and IB is high, i.e the KDMA that will be scored by the TA1/3 server is listed first
=> Add multi-KDMA targets for testing

align_system/algorithms/outlines_regression_adm_comparative.py, align_system/utils/incontext_utils.py
Adds true relevance values to the input output file for the comparative regression ADM. I don't think this is worthy of a changelog entry, but let me know if you'd like me to add one
=> Log true relevance for comp regression

CHANGELOG.md, align_system/algorithms/kaleido_adm.py, align_system/configs/experiment/phase1_evaluation/hybrid_kaleido_soartech_train.yaml, align_system/configs/experiment/phase1_evaluation/relevance_hybrid_kaleido_soartech_train.yaml, align_system/utils/alignment_utils.py
Adds the option to use cumulative KDE alignment with Kaleido, either with or without relevance.
- This config runs cumulative KDE alignment without relevance: `align_system/configs/experiment/phase1_evaluation/hybrid_kaleido_soartech_train.yaml`
- This config runs with relevance: `align_system/configs/experiment/phase1_evaluation/relevance_hybrid_kaleido_soartech_train.yaml`
=> Updating Kaleido Alignment Functions

pyproject.toml
By pinning commit SHA of itm-evaluation-client, aka swagger-client.
There is a bug due to upstream itm-evaluation-client changes.  Steps
```
python3 -m venv .venv
source .venv/bin/activate
pip install -e .
run_align_system
```
Get error
```
Error executing job with overrides: []
Error in call to target 'align_system.interfaces.input_output_file.InputOutputFileInterface':
TypeError('swagger_client.models.meta_info.MetaInfo() argument after ** must be a mapping, not MetaInfo')
full_key: interface
```
=> Fix dataset validation errors

.gitignore, align_system/algorithms/outlines_adm.py, align_system/prompt_engineering/outlines_prompts.py
Just leaving this here for now...
Mostly copy pastaed from #157 but made `get_dialogs` static so I don't have to load LLM to generate system prompt.
=>  Factor get_dialogs to static method in outlines_adm

align_system/prompt_engineering/outlines_prompts.py, poetry.lock, pyproject.toml, tests/data/expected_outputs/integration_tests/comp_reg_icl_adept_1/input_output.json, tests/data/expected_outputs/integration_tests/comp_reg_icl_adept_1/raw_align_system.log, tests/data/expected_outputs/integration_tests/comp_reg_icl_soartech_1/raw_align_system.log, tests/data/expected_outputs/integration_tests/hybrid_kaleido_adept_1/raw_align_system.log, tests/data/expected_outputs/integration_tests/multi_kdma_comp_reg_icl_adept_1/input_output.json, tests/data/expected_outputs/integration_tests/multi_kdma_comp_reg_icl_adept_1/raw_align_system.log, tests/data/expected_outputs/integration_tests/outlines_transformers_structured_baseline/input_output.json, tests/data/expected_outputs/integration_tests/outlines_transformers_structured_baseline/raw_align_system.log
This updates us to the latest available package versions for `transformers` (`4.49.0`) and `outlines` (`0.2.1`).  Note that the outputs are NOT identical compared to what our system generated before (see the changes to the integration test expected output files).  If we're to merge this we should not expect our Phase 1 Evalution ADMs to produce the same output (and scores) as before.  FWIW, you can always check out the previous version of the code if generating the same outputs is critical.  Also we'll need to clear out the outlines cache most likely as I think the format of that changed between versions.
I do think we'll have to accept this kind of drift to keep up with the latest available LLMs (via `transformers`), but would like to hear if there are major objections from folks on …
=> Update package versions and integration test expected outputs

CHANGELOG.md, align_system/algorithms/outlines_adm.py
Obvious in hindsight, it seems like the baseline shuffles the choices by default which will certainly cause some non-determinism.  I also added support in the outlines ADM for setting the outlines seed (which shouldn't affect things when using the Greedy sampler, but would allow you to get deterministic results with the multinomial sampler).
=> Determinism Fixes for Baseline ADM

align_system/algorithms/alignment_adm_component.py, align_system/algorithms/comparative_regression_adm_component.py, align_system/algorithms/misc_itm_adm_components.py, align_system/configs/adm/phase2_pipeline_zeroshot_comparative_regression.yaml, align_system/configs/adm_component/alignment/medical_urgency_scalar.yaml, align_system/configs/adm_component/misc/phase2_regression_rule_based_correction.yaml, align_system/configs/adm_component/regression/phase2_comparative.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Affiliation Focus-0.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Affiliation Focus-1.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Merit Focus-0.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Merit Focus-1.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Personal Safety-0.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Personal Safety-1.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Search or Stay-0.0.yaml, align_system/configs/alignment_target/ADEPT-Ph2-Search or Stay-1.0.yaml, align_system/configs/attribute/affiliation_focus.yaml, align_system/configs/attribute/medical_urgency.yaml, align_system/configs/attribute/merit_focus.yaml, align_system/configs/attribute/personal_safety.yaml, align_system/configs/attribute/search_or_stay.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_zeroshot_comparative_regression.yaml, align_system/configs/template/output_schema/phase2_comparative_regression_choice.yaml, align_system/configs/template/prompt/phase2_comparative_regression.yaml, align_system/configs/template/scenario_description/phase2.yaml, align_system/prompt_engineering/outlines_prompts.py, example_data/input_output_files/phase2_june_collab/affiliation_focus_input_output.json, example_data/input_output_files/phase2_june_collab/merit_focus_input_output.json, example_data/input_output_files/phase2_june_collab/personal_safety_focus_input_output.json, example_data/input_output_files/phase2_june_collab/search_vs_stay_input_output.json
- Built off of [dev/kaleido-ph2-june-collab](https://github.com/ITM-Kitware/align-system/tree/dev/kaleido-ph2-june-collab) PR #181 
- Adds the initial phase2 zeroshot comparative regression ADM
- Adds high and low single targets for Phase 2 KDMAs
- Does not have relevance prediction.
- Adds "medical urgency" as another KDMA which is always regressed so that we can compute medical delta
- Currently is using old avg distance alignment function (not factoring in medical urgency)
- Reasoning statements have been moved from choice level to probe level so they are more "comparative" and it is faster
Example calls to run each KDMA with high targets:
```
run_align_system +experiment=phase2_june_collab/pipeline_zeroshot_comparative_regression +alignment_target='ADEPT-Ph2-Affiliation Focus-1.0' …
```
=> Phase2 Initial ZeroShot Comparative Regression ADM

align_system/algorithms/misc_itm_adm_components.py, align_system/configs/adm/phase2_pipeline_oracle.yaml, align_system/configs/adm_component/misc/oracle_justification.yaml, align_system/configs/adm_component/misc/oracle_regression.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_oracle.yaml
Adds phase2 pipeline oracle ADM which uses ground truth scores as regressed values and `medical_urgency_scalar` alignment.
Example command to run:
```
run_align_system +experiment=phase2_june_collab/pipeline_oracle interface.scenario_ids=[June2025-AF-train] +alignment_target=june2025/ADEPT-June2025-affiliation-1.0
```
=> Adding phase2 pipeline oracle adm

CHANGELOG.md, align_system/algorithms/comparative_regression_adm_component.py, align_system/algorithms/icl_adm_component.py, align_system/configs/adm/phase2_pipeline_fewshot_comparative_regression.yaml, align_system/configs/adm_component/icl/phase2_comparative.yaml, align_system/configs/adm_component/regression/phase2_comparative_no_template.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo.yaml, align_system/interfaces/input_output_file.py, align_system/prompt_engineering/outlines_prompts.py, align_system/utils/hydrate_state.py, align_system/utils/incontext_utils.py
Adding phase2 fewshot ADM.
Example call to run:
```
run_align_system +experiment=phase2_june_collab/pipeline_fewshot_comparative_regression_loo interface.scenario_ids=[June2025-AF-train] +alignment_target=june2025/ADEPT-June2025-affiliation-1.0
```
Currently to run this I have to comment out lines 4-11 and 18-32 in `align_system/utils/hydrate_state.py` will look into a better solution before merging.
=> Phase2 fewshot ADM

align_system/algorithms/misc_itm_adm_components.py, align_system/algorithms/relevance_adm_component.py, align_system/configs/adm/phase2_pipeline_fewshot_comparative_regression_predict_most_relevant.yaml, align_system/configs/adm_component/relevance/predict_most_relevant.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_predict_most_relevant.yaml, align_system/prompt_engineering/outlines_prompts.py
Adds a fewshot comp reg ADM with the added step of predicting most relevant attribute in multi-attribute targets. 
Example call to run: 
```
run_align_system +experiment=phase2_june_collab/pipeline_fewshot_comparative_regression_loo_predict_most_relevant +alignment_target=june2025/ADEPT-June2025-affiliation_merit-0.0_0.0.yaml
```
=> Adding llm-based most relevant attribute prediction step

align_system/configs/adm/phase2_pipeline_fewshot_comparative_regression_kaleido_relevance.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_kaleido_relevance.yaml
Adds mashup ADM which uses Kaleido for relevance prediction and fewshot comp. reg. for score regression.
Example call to run:
```
run_align_system +experiment=phase2_june_collab/pipeline_fewshot_comparative_regression_loo_kaleido_relevance +alignment_target=june2025/ADEPT-June2025-affiliation_merit-0.0_0.0.yaml
```
In the future the speed could be improved by only regressing the attribute Kaleido predicted as relevant.
=> Adding fewshot comp reg and kaleido relevance mashup ADM

align_system/algorithms/relevance_adm_component.py, align_system/configs/adm/phase2_pipeline_fewshot_comparative_regression_bert_relevance.yaml, align_system/configs/adm_component/relevance/bert_relevance.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_bert_relevance.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_predict_most_relevant.yaml
Adds an ADM that uses the BERT similairty between the current probe and ICL examples to determine which attribute is most relevant. 
Example call to run:
```
run_align_system +experiment=phase2_june_collab/pipeline_fewshot_comparative_regression_loo_bert_relevance +alignment_target=june2025/ADEPT-June2025-affiliation_merit-0.0_0.0.yaml
```
=> Bert similarity based relevance prediction

align_system/interfaces/ta3_caci_action_based_service.py
Phase2 data has been updated to move the scenario description out from the `state.unstructured` field into the unstructured field for the scenario (and it's been put into the `threat_state.unstructured` as a convenience for us).  This PR "hacks" the unstructured state text coming back from the server to put that scenario text in front again (so the Phase2 ADMs don't need to change anything).
=> Prepend the scenario unstructured to the scene/probe unstructured

README.md, docs/developer_setup.md
Added instructions to README to set up a hugging face personal access token, allows accessing 'gated' models for which you have to accept the T&Cs on the hugging face website.
=> Instructions for hugging face token cache

align_system/algorithms/alignment_adm_component.py, align_system/tests/test_alignment_adm_component.py
- If target is exactly the midpoint, we now choose the medically-needy patient, instead of not voting for that KDMA (which made it a random choice in the single KDMA case)
- Additionally, if multiple patients receive the same number of votes, we now choose the "first" patient instead of randomly choosing, to remove that source of non-determinism
- There is still one case where we don't vote: both patients receive the same medical *and* same attribute scores. In the multi-KDMA case, this is equivalent to ignoring that KDMA (decision would be based on the other KDMA votes). In the single KDMA case, neither patient would receive a vote, i.e. tied at 0 votes, so we fall back to choosing the first patient as described in the previous bullet
=> Remove non-determinism from midpoint alignment functions

align_system/configs/experiment/phase2_july_collab/pipeline_baseline_DeepSeek-R1-Distill-Qwen-7B_live_eval_test.yaml, align_system/configs/experiment/phase2_july_collab/pipeline_baseline_Meta-Llama-3-8B-Instruct_live_eval_test.yaml, align_system/configs/experiment/phase2_july_collab/pipeline_baseline_Meta-Llama-3.2-3B-Instruct_live_eval_test.yaml, align_system/configs/experiment/phase2_july_collab/pipeline_baseline_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_20icl_10samples_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_20icl_handpicked_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_20icl_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_DeepSeek-R1-Distill-Qwen-7B_20icl_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_Meta-Llama-3-8B-Instruct_20icl_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_Meta-Llama-3.2-3B-Instruct_20icl_live_eval.yaml, align_system/configs/experiment/phase2_july_collab/rq2_pipeline_fewshot_comparative_regression_bert_relevance_live_eval.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl_deepseek-r1-qwen-7b.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl_gemma2-9b-it.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl_llama3-8b.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl_llama3.2-3b.yaml, align_system/configs/experiment/phase2_june_collab/pipeline_fewshot_comparative_regression_loo_20icl_llama3.3-70b.yaml
(In the future it's probably better to create a subdirectory inside of `phase2_july_collab` for each of `rq1` and `rq2`)
=> Add July 2025 RQ2 eval configs
